# Generated by Django 5.2.16 on 2026-07-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testimonial",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.AddField(
            model_name="galleryalbum",
            name="category",
            field=models.CharField(blank=True, default="Headquarters", max_length=100),
        ),
        migrations.AddField(
            model_name="galleryalbum",
            name="date_taken",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="salary_range",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="is_featured",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Reviewing", "Reviewing"),
                    ("In Review", "In Review"),
                    ("Interviewing", "Interviewing"),
                    ("Offered", "Offered"),
                    ("Rejected", "Rejected"),
                    ("Hired", "Hired"),
                ],
                default="New",
                max_length=20,
            ),
        ),
    ]
